### PR TITLE
Keep only some CSS rules and assets from Sandstone, drop Tabzilla

### PR DESCRIPTION
**Pull request by flodolo**
Tabzilla should not have a long life anyway. It's already been replaced with a static image in several pages (e.g. [firefox/os](https://www.mozilla.org/firefox/os))

### CODE REVIEW

**Comment by pascalchevrel** [comment]
I see an alignment issues of locale codes on the home page with the shortened css, not found yet the cause

**Comment by flodolo** [comment]
Locale code you mean the box on the top right or something else? I moved it around on purpose, that's the only thing that should have some differences together with the feed bar.

**Comment by pascalchevrel** [comment]
no, the list of locales on the home page on 5 columns

**Comment by flodolo** [comment]
OK, I see the problem (first locale of the first column), I guess it's a lack of reset. Let me check.

**Comment by flodolo** [comment]
Added a separate commit to fix the home page.

**Pull request merged**
